name: "Terraform Automation"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Job"
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # Yahan humne har step mein 'working-directory' alag se likh diya hai
      # Isse galti hone ka chance khatam ho jata hai
      - name: Terraform Init
        run: terraform init
        working-directory: CodeSamples/Terraform/terraform-state-04-04-2026

      - name: Terraform Plan
        run: terraform plan
        working-directory: CodeSamples/Terraform/terraform-state-04-04-2026

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: CodeSamples/Terraform/terraform-state-04-04-2026
